[build]
    publish = "/dist"
    command = "npm run build"


[dev]
    publish = "/dist"
    framework = "vite"


[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
